## Names for the data and machine parameter settings
names_cameca <- tibble::tibble(
  cameca = c(
    "N.rw",
    "n.rw",
    "N.pr",
    "Xt.pr",
    "species.nm",
    "t.nm",
    "bl.nm",
    "file.nm",
    "sample.nm",
    "date.mt",
    "x.mt",
    "y.mt",
    "z.mt",
    "Raw data file",
    "Block number",
    "Meas. per block",
    "Rejection(sigma)",
    "Slit Preset",
    "Lens Preset",
    "Pre Sputtering Time (s)",
    "Raster (um)",
    "Scanning On",
    "Blanking",
    "Raster",
    "Tuning Mode",
    "Regulation Mode",
    "Check every (fr.)",
    "Secondary Ion Beam Centering",
    "during Acq",
    "Width Horizontal(V)",
    "Vertical(V)",
    "E0S Centering",
    "Width(V)",
    "E0P Offset (V)",
    "Primary Current before acq",
    "after acq",
    "FC Background before acq",
    "FC Background after acq"
     ),
# New names for internal processing
  point = c(
    "N.rw",
    "n.rw",
    "N.pr",
    "Xt.pr",
    "species.nm",
    "t.nm",
    "bl.nm",
    "file.nm",
    "sample.nm",
    "date.mt",
    "x.mt",
    "y.mt",
    "z.mt",
    "file_raw.mt",
    "bl_num.mt",
    "meas_bl.mt",
    "rejection.mt",
    "slit.mt",
    "lens.mt",
    "presput.mt",
    "rast_com.mt",
    "scan.mt",
    "blank_rast.mt",
    "raster.mt",
    "tune.mt",
    "reg_mode.mt",
    "chk_frm.mt",
    "sec_ion_cent.mt",
    "acq.mt",
    "width_hor.mt",
    "width_ver.mt",
    "E0S_cent.mt",
    "width_V.mt",
    "E0P_off.mt",
    "prim_cur_start.mt",
    "prim_cur_after.mt",
    "FC_start.mt",
    "FC_after.mt"
     ),
  definition = c(
  "Raw ion count",
  "Number of observations",
  "Proccesed ion count",
  "Ion count rate",
  "Ion species",
  "Time increment",
  "Block",
  "File name",
  "Sample name",
  "Date and time",
  "x coordinate",
  "y coordinate",
  "z coordinate",
  "Raw data file",
  "Block number",
  "Meas. per block",
  "Rejection(sigma)",
  "Slit Preset",
  "Lens Preset",
  "Pre Sputtering Time (s)",
  "Raster (um)",
  "Scanning On",
  "Blanking",
  "Raster",
  "Tuning Mode",
  "Regulation Mode",
  "Check every (fr.)",
  "Secondary Ion Beam Centering",
  "during Acq",
  "Width Horizontal(V)",
  "Vertical(V)",
  "E0S Centering",
  "Width(V)",
  "E0P Offset (V)",
  "Primary Current before acq",
  "after acq",
  "FC Background before acq",
  "FC Background after acq"
  ),
  use = c(rep("data", 4), rep("group", 5), rep("meta", 29))
  )

usethis::use_data(names_cameca, overwrite = TRUE)
usethis::use_data(names_cameca, internal = TRUE, overwrite = TRUE)
