---
title: "IC-diagnostics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{IC-diagnostics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(point)
devtools::load_all(".")
```


```{r warning=FALSE}

# Use point_example() to access the examples bundled with this package in the
# inst/extdata directory. The examples directories are named:
# 2020-01-17-TREASURE and "2018-01-19-GLENDON"

# raw data containing 13C and 12C counts on carbonate
tb.rw <- read_IC(point_example("2018-01-19-GLENDON"))

# processing raw ion count data
tb.pr <- cor_IC(tb.rw, 
                N = N.rw, 
                t = t.rw, 
                Det = det_type.mt, 
                deadtime = 44, 
                thr_PHD = 50)

# CAMECA style augmented datafile
tb.aug <- diag_R(tb.pr,
                 method = "standard",
                 Moreargs = quos(Xt = Xt.pr,
                                 N = N.pr,
                                 species = species.nm,
                                 ion1 = "13C",
                                 ion2 = "12C",
                                 .named = TRUE),
                 file.nm) %>%
              filter(flag == "good") # filter the analysis that pass the test

# descriptive an predictive statistics for 13C/12C ratios (blockwise)
  tb.R.bl <- stat_R(tb.aug, 
                    Xt.pr, 
                    N.pr, 
                    species = species.nm, 
                    ion1 = "13C", 
                    ion2 = "12C",
                    file.nm, 
                    bl.mt,  
                    latex = FALSE, 
                    output = "sum")
  
# augmented descriptive an predictive statistics for 13C/12C ratios (global)
  tb.R.aug <- stat_R(tb.aug, 
                     Xt.pr, 
                     N.pr, 
                     species = species.nm, 
                     ion1 = "13C", 
                     ion2 = "12C",
                     file.nm, 
                     latex = FALSE, 
                     output = "sum")
```

