#' The plot types for diagnostic tests available in \code{point}
#'
#' A dataset containing the diagnostic point variable names
#'
#' @format A data frame with 2 rows and 3 variables:
#' \describe{
#'   \item{argument}{argument names in point}
#'   \item{point}{variable names generated by point::diag_R()}
#'   \item{use}{usage in point package}
#' }
#' @source \code{point::\link[point:diag_R]{diag_R}()}
"names_diag"
