#' Process raw ion count data
#'
#' \code{proc_Xt} function for processing ion count data
#'
#' Ion count data consisting of time-incremented integer values are process. These functions
#' are currently only supported for data generated by a NanoSIMS50L. Raw ion
#' count data and accompayning is extracted and collated into a single tible
#' from text files with the extensions \emph{.is_txt} and \emph{.stat},
#' respectively. These files can be found in the directories associated with the
#' SIMS measurements.
#'
#' @param df A tibble containing raw ion count data
#' @param Xt A variable constituting the ion count rate
#' @param N A variable constituting the ion counts
#' @param deadtime A numeric value for the deadtime of the EM
#' @param ... Variables for grouping
#'
#' @return A \code{\link[tibble:tibble]{tibble}} containing processed
#' ion count data and metadata
#'
#' @examples
#' # Use point_example() to access the examples bundled with this package in the
#' # inst/extdata directory. The examples directories are named:
#' # 2020-01-17-TREASURE and "2018-01-19-GLENDON"
#'
#' # raw data containing 13C and 12C counts on carbonate
#' tb.rw <- read_IC(point_example("2018-01-19-GLENDON"))
#'
#' # processing raw ion count data
#' tb.pr <- cor_IC(tb.rw, N.rw, t.rw, det_type.mt)
#'
#' @export
cor_IC <-function(df, N, t, Det, deadtime = 44, thr_PHD = 50){

  stopifnot(tibble::is_tibble(df))
  stopifnot(is.numeric(deadtime))

  N <- enquo(N)
  t <- enquo(t)
  Det <- enquo(Det)

  df <- df %>%
# Time increments
          mutate(dt = min(!!t),
# Count rates
                 Xt.rw = !!N / dt) %>%
# Deadtime correction on count rates
          mutate(Xt.pr = if_else(!!Det == "EM",
                                 Xt.rw / (1 - (Xt.rw * deadtime * 10^-9)),
                                 Xt.rw ),
# Deadtime correction on counts
                 N.pr = if_else(!!Det == "EM",
                                (Xt.rw / (1 - (Xt.rw * deadtime * 10^-9))) * dt,
                                Xt.rw )) %>%
# Yield correction on count rates
            mutate(Y = if_else(is.na(mean_PHD),
                               NA_real_,
                               ppois(thr, lambda = mean_PHD, lower.tail = FALSE)),
                   Xt.pr = if_else(is.na(PHD), Xt.pr,  Xt.pr / Y),
                   N.pr = if_else(is.na(PHD),N.pr , Xt.pr * dt))

  }
