#' Process raw ion count data
#'
#' \code{proc_Xt} function for processing ion count data
#'
#' Ion count data consisting of time-incremented integer values are process. These functions
#' are currently only supported for data generated by a NanoSIMS50L. Raw ion
#' count data and accompayning is extracted and collated into a single tible
#' from text files with the extensions \emph{.is_txt} and \emph{.stat},
#' respectively. These files can be found in the directories associated with the
#' SIMS measurements.
#'
#' @param df A tibble containing raw ion count data
#' @param Xt A variable constituting the ion count rate
#' @param N A variable constituting the ion counts
#' @param deadtime A numeric value for the deadtime of the EM
#' @param ... Variables for grouping
#'
#' @export
cor_IC <-function(df, N, t, Det, deadtime = 44){

  stopifnot(tibble::is_tibble(df))
  stopifnot(is.numeric(deadtime))

  N <- enquo(N)
  t <- enquo(t)
  Det <- enquo(Det)

  df <- df %>%
# time increments
          mutate(dt = min(!!t),
# count rates
                 Xt.rw = !!N / dt) %>%
# deadtime correction on count rates
          mutate(Xt.pr = if_else(!!Det == "EM",
                                 Xt.rw / (1 - (Xt.rw * deadtime * 10^-9)),
                                 Xt.rw ),
# deadtime correction on couts
                 N.pr = if_else(!!Det == "EM",
                                (Xt.rw / (1 - (Xt.rw * deadtime * 10^-9))) * dt,
                                Xt.rw ))
  }
